version: '3.7'

x-common-variables: &common-variables
  PSQL_DATABASE: plant_care
  POSTGRES_USER: plant_care
  POSTGRES_PASSWORD: 1234

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      <<: *common-variables
    volumes: 
      - db:/var/lib/postgresql/data
      - "./server/models/plant_care_DB_setup.sql:/docker-entrypoint-initdb.d/create_tables.sql"
    ports:
      - "5432:5432"
    networks:
      - app-network

  server:
    container_name: plantcare-node-server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: plantcare-server
    depends_on:
      - db
    command: npm start
    volumes:
      - ./server/:/app
      - app/node_modules
    ports:
      - "4000:4000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  
  client:
    build:
      context: ./client/plantcare
      dockerfile: Dockerfile
    image: plantcare-client
    container_name: plantcare-react-client
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    node_modules:
    web-root:
      driver: local
    db:
      driver: local